import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "@rainbow-me/rainbowkit/styles.css";
import { headers } from "next/headers";
import Providers from "./provider";
import { Toaster } from "@/components/ui/sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = await headers();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers cookie={cookie.get("cookie")}>{ children}</Providers>
        <Toaster richColors={true} duration={10000} visibleToasts={4} />

      </body>
    </html>
  );
}


// import "./globals.css";
// import "@rainbow-me/rainbowkit/styles.css";

// import { Inter } from "next/font/google";
// import type { Metadata } from "next";
// import { headers } from "next/headers";

// import Providers from "./providers";

// export const metadata: Metadata = {
//   title: "Omni Pump",
//   // description: "Discover JatCoin, a decentralized stablecoin backed by the Jatique protocol and governed by the Jatique DAO. Learn how JatCoin brings stability, security, and decentralization to the DeFi ecosystem.",
//   // keywords: "JatCoin, stablecoin, decentralized finance, DeFi, Jatique protocol, Jatique DAO, cryptocurrency, blockchain, digital currency",
//   robots: "index, follow",


// };

// const inter = Inter({ subsets: ["latin"] });

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const cookie = headers().get("cookie");

//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Providers cookie={cookie}>{children}</Providers>
//       </body>
//     </html>
//   );
// }
